openapi: 3.0.3
info:
  title: Laravel REST API
  version: 1.0.0

servers:
  - url: http://localhost:60080/api/v1

paths:
  $ref: './paths.yaml'

components:
  $ref: './components.yaml'

security:
  - bearerAuth: []
